---
swagger: "2.0"
info: {}
basePath: "/"
tags:
- name: "employees"
paths:
  /employees:
    get:
      tags:
      - "employees"
      summary: "Get all employees"
      description: "Interact with employee resources"
      operationId: "getAllEmployees"
      consumes:
      - "application/json; charset=UTF-8"
      produces:
      - "application/json; charset=UTF-8"
      parameters:
      - name: "limit"
        in: "query"
        description: "limits the result set"
        required: false
        type: "integer"
        default: "10"
        format: "int32"
      - name: "offset"
        in: "query"
        description: "the offset"
        required: false
        type: "integer"
        default: "0"
        format: "int32"
      - name: "search"
        in: "query"
        description: "search for names that contains the given string. not case sensetive. "
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/EmployeesResponse"
    post:
      tags:
      - "employees"
      summary: "Creates a new employee"
      description: ""
      operationId: "createEmployee"
      consumes:
      - "application/json; charset=UTF-8"
      parameters:
      - in: "body"
        name: "body"
        description: "employee data"
        required: false
        schema:
          $ref: "#/definitions/EmployeeData"
      responses:
        default:
          description: "successful operation"
  /employees/{employeeId}:
    get:
      tags:
      - "employees"
      summary: "Get an employees wit a certain ID"
      description: ""
      operationId: "getEmployee"
      consumes:
      - "application/json; charset=UTF-8"
      produces:
      - "application/json; charset=UTF-8"
      parameters:
      - name: "employeeId"
        in: "path"
        description: "the id of the employee"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/EmployeeResponse"
        400:
          description: "Invalid ID supplied"
    put:
      tags:
      - "employees"
      summary: "Updates a given employee"
      description: ""
      operationId: "updateEmployee"
      consumes:
      - "application/json; charset=UTF-8"
      parameters:
      - name: "employeeId"
        in: "path"
        description: "the id of the employee to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "the new employee data"
        required: false
        schema:
          $ref: "#/definitions/EmployeeData"
      responses:
        default:
          description: "successful operation"
    delete:
      tags:
      - "employees"
      summary: "Deletes an employee"
      description: ""
      operationId: "deleteEmployee"
      consumes:
      - "application/json; charset=UTF-8"
      parameters:
      - name: "employeeId"
        in: "path"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
  /employees/{employeeId}/projectdays:
    get:
      tags:
      - "employees"
      summary: "Get the project day for an employee"
      description: ""
      operationId: "getAllProjectDays"
      consumes:
      - "application/json; charset=UTF-8"
      produces:
      - "application/json; charset=UTF-8"
      parameters:
      - name: "employeeId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ProjectDaysResponse"
definitions:
  YearMonth:
    properties:
      year:
        type: "integer"
        format: "int32"
      month:
        type: "string"
        enum:
        - "JANUARY"
        - "FEBRUARY"
        - "MARCH"
        - "APRIL"
        - "MAY"
        - "JUNE"
        - "JULY"
        - "AUGUST"
        - "SEPTEMBER"
        - "OCTOBER"
        - "NOVEMBER"
        - "DECEMBER"
      leapYear:
        type: "boolean"
        default: false
      monthValue:
        type: "integer"
        format: "int32"
  ProjectDaysResponse:
    properties:
      month:
        $ref: "#/definitions/YearMonth"
      daysCount:
        type: "integer"
        format: "int32"
  EmployeeData:
    required:
    - "name"
    properties:
      name:
        type: "string"
  EmployeesResponse:
    properties:
      totalCount:
        type: "integer"
        format: "int64"
        description: "the total amount of employees matching the request."
      employees:
        type: "array"
        items:
          $ref: "#/definitions/EmployeeResponse"
      limit:
        type: "integer"
        format: "int32"
      offset:
        type: "integer"
        format: "int32"
      search:
        type: "string"
      links:
        type: "array"
        items:
          $ref: "#/definitions/LinkResponse"
  EmployeeResponse:
    properties:
      id:
        type: "string"
      name:
        type: "string"
      links:
        type: "array"
        items:
          $ref: "#/definitions/LinkResponse"
  LinkResponse:
    properties:
      rel:
        type: "string"
        readOnly: true
      href:
        type: "string"
        readOnly: true
