template: Hello, %s!
mongoDB:
 host: 192.168.99.100
 port: 27017
 databaseName: test
 employeeCollectionName: employees
# the only required property is resourcePackage, for more config options see below
swagger:
  resourcePackage: de.philipphauer.prozu.rest